# Generated by Django 3.2.4 on 2021-06-30 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('body', models.TextField(verbose_name='Post body')),
                ('image', models.ImageField(upload_to='posts', verbose_name='Image path')),
                ('legend', models.CharField(max_length=200, verbose_name='Legend')),
            ],
        ),
    ]
